disabled_rules:
  - file_length
  - line_length
  - todo
  - type_body_length

included:
  - Sources/CryptomatorCryptoLib
  - Tests/CryptomatorCryptoLibTests
excluded:
  - Tests/CryptomatorCryptoLibTests/XCTestManifests.swift

identifier_name:
  min_length: 1
  max_length: 50
inclusive_language:
  override_allowed_terms: ["masterkey"]
type_name:
  max_length: 50
  allowed_symbols: "_"
