#if !canImport(ObjectiveC)
import XCTest

extension AesCtrTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AesCtrTests = [
        ("testDecrypt", testDecrypt),
        ("testEncrypt", testEncrypt),
    ]
}

extension AesSivTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AesSivTests = [
        ("testCmac1", testCmac1),
        ("testCmac2", testCmac2),
        ("testCmac3", testCmac3),
        ("testCmac4", testCmac4),
        ("testCtr", testCtr),
        ("testDecrypt", testDecrypt),
        ("testEncrypt", testEncrypt),
        ("testS2v", testS2v),
    ]
}

extension CryptorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CryptorTests = [
        ("testCalculateCiphertextSize", testCalculateCiphertextSize),
        ("testCalculateCleartextSize", testCalculateCleartextSize),
        ("testCalculateCleartextSizeWithInvalidCiphertextSize", testCalculateCleartextSizeWithInvalidCiphertextSize),
        ("testCreateHeader", testCreateHeader),
        ("testDecryptHeader", testDecryptHeader),
        ("testEncryptAndDecryptContent", testEncryptAndDecryptContent),
        ("testEncryptAndDecryptName", testEncryptAndDecryptName),
        ("testEncryptAndDecryptSingleChunk", testEncryptAndDecryptSingleChunk),
        ("testEncryptDirId", testEncryptDirId),
        ("testEncryptHeader", testEncryptHeader),
    ]
}

extension MasterkeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MasterkeyTests = [
        ("testCreateFromMasterkeyFile", testCreateFromMasterkeyFile),
        ("testCreateFromMasterkeyFileWithInvalidVersionMac", testCreateFromMasterkeyFileWithInvalidVersionMac),
        ("testCreateFromMasterkeyFileWithMalformedJson1", testCreateFromMasterkeyFileWithMalformedJson1),
        ("testCreateFromMasterkeyFileWithMalformedJson2", testCreateFromMasterkeyFileWithMalformedJson2),
        ("testCreateFromMasterkeyFileWithMalformedJson3", testCreateFromMasterkeyFileWithMalformedJson3),
        ("testCreateFromMasterkeyFileWithWrongPassword", testCreateFromMasterkeyFileWithWrongPassword),
        ("testExportEncrypted", testExportEncrypted),
        ("testWrapAndUnwrapKey", testWrapAndUnwrapKey),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AesCtrTests.__allTests__AesCtrTests),
        testCase(AesSivTests.__allTests__AesSivTests),
        testCase(CryptorTests.__allTests__CryptorTests),
        testCase(MasterkeyTests.__allTests__MasterkeyTests),
    ]
}
#endif
